# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executing', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('run_frequency', models.PositiveIntegerField(default=1440)),
                ('last_run', models.DateTimeField(default=django.utils.timezone.now)),
                ('instance', models.TextField()),
                ('args', models.TextField()),
                ('kwargs', models.TextField()),
                ('queued', models.BooleanField(default=True)),
            ],
        ),
    ]
